const obj: Record<string, string> = {
  create: "ایجاد",
  createMany: "ایجاد گروهی",
  update: "ویرایش",
  updateMany: "ویرایش گروهی",
  delete: "حذف",
  deleteMany: "حذف گروهی",
  upsert: "افزایش",
  email: "ایمیل",
  sms: "پیامک",
  image: "تصویر",
  text: "متن",
  online: "آنلاین",
  group: "دسته‌بندی محصولات",
  specific: "محصولات خاص",
  alert: "هشدار",
  successful: "موفقیت آمیز",
  notification: "اعلان",
  warning: "اخطار",
  authenticated: "کاربران لاگین",
  guest: "همه کاربران",
  category: "دسته‌بندی",
  active: "فعال",
  deActive: "غیر فعال",
  DEDUCT: "برداشت",
  checking: "در حال بررسی",
  checked: "بررسی شده",
  CHARGE: "واریز",
  card: "کارت",
  bulk: "عمده",
  country_based: "بر اساس کشور",
  not_active: "غیر فعال",
  personal_info: "اطلاعات شخصی",
  pending: "در انتظار بررسی",
  approve: "تایید شده",
  denied: "عدم تایید",
  product: "محصول",
  PRODUCT: "محصول",
  post: "مقاله",
  news: "خبر",
  blog: "بلاگ",
  processing: "درحال بررسی",
  GetInformation: "دریافت اطلاعات",
  completed: "تکمیل شده",
  unpaid: "پرداخت نشده",
  online_payment: "پرداخت آنلاین",
  transfer_to_wallet: "انتقال به کیف پول",
  canceled: "لغو شده",
  archived: "بایگانی‌شده",
  customer_no_response: "عدم پاسخ مشتری",
  incorrect_info: "اطلاعات اشتباه",
  ready_for_delivery: "آماده برای تحویل",
  in_progress: "درحال بررسی",
  under_review: "درحال بررسی",
  get_info: "دریافت اطلاعات",
  wallet: "کیف پول",
  purchased: "خریداری شده",
  not_purchased: "خریداری نشده",
  paystar: "پی‌استار",
  viewed: "مشاهده کرد",
  no_acted: "تغییری اعمال نشده",
  acted: "عملیات تغییر ثبت شد",
  UnitedStates: "آمریکا",
  Canada: "کانادا",
  UnitedKingdom: "انگلیس",
  Turkey: "ترکیه",
  UnitedArabEmirates: "امارات متحده عربی",
  Afghanistan: "افغانستان",
  Albania: "آلبانی",
  Algeria: "الجزایر",
  Angola: "آنگولا",
  Anguilla: "آنگویلا",
  AntiguaAndBarbuda: "آنتیگوا و باربودا",
  Argentina: "آرژانتین",
  Armenia: "ارمنستان",
  Australia: "استرالیا",
  Austria: "اتریش",
  Azerbaijan: "آذربایجان",
  Bahamas: "باهاما",
  Bahrain: "بحرین",
  Bangladesh: "بنگلادش",
  Barbados: "باربادوس",
  Belarus: "بلاروس",
  Belgium: "بلژیک",
  Belize: "بلیز",
  Benin: "بنین",
  Bermuda: "برمودا",
  Bhutan: "بوتان",
  Bolivia: "بولیوی",
  BosniaAndHerzegovina: "بوسنی و هرزگوین",
  Botswana: "بوتسوانا",
  Brazil: "برزیل",
  BritishVirginIslands: "جزایر ویرجین بریتانیا",
  BruneiDarussalam: "برونئی دارالسلام",
  Bulgaria: "بلغارستان",
  BurkinaFaso: "بورکینافاسو",
  Cambodia: "کامبوج",
  Cameroon: "کامرون",
  CapeVerde: "کیپ ورد",
  CaymanIslands: "جزایر کیمن",
  Chad: "چاد",
  Chile: "شیلی",
  China: "چین",
  Colombia: "کلمبیا",
  CostaRica: "کاستاریکا",
  CôtedIvoire: "ساحل عاج",
  Croatia: "کرواسی",
  Cyprus: "قبرس",
  Czechia: "جمهوری چک",
  DemocraticRepublicoftheCongo: "جمهوری دموکراتیک کنگو",
  Denmark: "دانمارک",
  Dominica: "دومینیکا",
  DominicanRepublic: "جمهوری دومینیکن",
  Ecuador: "اکوادور",
  Egypt: "مصر",
  ElSalvador: "السالوادور",
  Estonia: "استونی",
  Eswatini: "اسواتینی",
  Fiji: "فیجی",
  Finland: "فنلاند",
  France: "فرانسه",
  Gabon: "گابن",
  Gambia: "گامبیا",
  Georgia: "گرجستان",
  Germany: "آلمان",
  Ghana: "غنا",
  Greece: "یونان",
  Grenada: "گرنادا",
  Guatemala: "گواتمالا",
  GuineaBissau: "گینه بیسائو",
  Guyana: "گویان",
  Honduras: "هندوراس",
  HongKong: "هنگ کنگ",
  Hungary: "مجارستان",
  Iceland: "ایسلند",
  India: "هند",
  Indonesia: "اندونزی",
  Iraq: "عراق",
  Ireland: "ایرلند",
  Israel: "اسرائیل",
  Italy: "ایتالیا",
  Jamaica: "جامائیکا",
  Japan: "ژاپن",
  Jordan: "اردن",
  Kazakhstan: "قزاقستان",
  Kenya: "کنیا",
  Kosovo: "کوزوو",
  Kuwait: "کویت",
  Kyrgyzstan: "قرقیزستان",
  Laos: "لائوس",
  Latvia: "لتونی",
  Lebanon: "لبنان",
  Liberia: "لیبریا",
  Libya: "لیبی",
  Lithuania: "لیتوانی",
  Luxembourg: "لوکزامبورگ",
  Macao: "ماکائو",
  Madagascar: "ماداگاسکار",
  Malawi: "مالاوی",
  Malaysia: "مالزی",
  Maldives: "مالدیو",
  Mali: "مالی",
  Malta: "مالت",
  Mauritania: "موریتانی",
  Mauritius: "موریس",
  Mexico: "مکزیک",
  Micronesia: "میکرونزی",
  Moldova: "مولداوی",
  Mongolia: "مغولستان",
  Montenegro: "مونته‌نگرو",
  Montserrat: "مونت‌سرات",
  Morocco: "مراکش",
  Mozambique: "موزامبیک",
  Myanmar: "میانمار",
  Namibia: "نامیبیا",
  Nauru: "نائورو",
  Nepal: "نپال",
  Netherlands: "هلند",
  NewZealand: "نیوزیلند",
  Nicaragua: "نیکاراگوئه",
  Niger: "نیجر",
  Nigeria: "نیجریه",
  NorthMacedonia: "مقدونیه شمالی",
  Norway: "نروژ",
  Oman: "عمان",
  Pakistan: "پاکستان",
  Palau: "پالائو",
  Panama: "پاناما",
  PapuaNewGuinea: "پاپوآ گینه نو",
  Paraguay: "پاراگوئه",
  Peru: "پرو",
  Philippines: "فیلیپین",
  Poland: "لهستان",
  Portugal: "پرتغال",
  Qatar: "قطر",
  RepublicoftheCongo: "جمهوری کنگو",
  Romania: "رومانی",
  Russia: "روسیه",
  Rwanda: "رواندا",
  SaintKittsAndNevis: "سنت کیتس و نویس",
  SaintLucia: "سنت لوسیا",
  SaintVincentandtheGrenadines: "سنت وینسنت و گرنادین‌ها",
  SaoTomeAndPrincipe: "سائوتومه و پرنسیپ",
  SaudiArabia: "عربستان سعودی",
  Senegal: "سنگال",
  Serbia: "صربستان",
  Seychelles: "سیشل",
  SierraLeone: "سیرالئون",
  Singapore: "سنگاپور",
  Slovakia: "اسلواکی",
  Slovenia: "اسلوونی",
  SolomonIslands: "جزایر سلیمان",
  SouthAfrica: "آفریقای جنوبی",
  SouthKorea: "کره جنوبی",
  Spain: "اسپانیا",
  SriLanka: "سریلانکا",
  Suriname: "سورینام",
  Sweden: "سوئد",
  Switzerland: "سوئیس",
  Taiwan: "تایوان",
  Tajikistan: "تاجیکستان",
  Tanzania: "تانزانیا",
  Thailand: "تایلند",
  Tonga: "تونگا",
  TrinidadAndTobago: "ترینیداد و توباگو",
  Tunisia: "تونس",
  Turkmenistan: "ترکمنستان",
  TurksAndCaicosIslands: "جزایر تورکس و کایکوس",
  Uganda: "اوگاندا",
  Ukraine: "اوکراین",
  Uruguay: "اروگوئه",
  Uzbekistan: "ازبکستان",
  Vanuatu: "وانواتو",
  Venezuela: "ونزوئلا",
  Vietnam: "ویتنام",
  Yemen: "یمن",
  Zambia: "زامبیا",
  Zimbabwe: "زیمبابوه",
  zibal: "زیبال",
  scraper_fail: "ناموفق",
};

export const translate = (e?: string | null, t?: string): string => {
  if (!e) return "-";

  t = t ?? "fa";

  if (t !== "fa") return e;

  if (obj[e]) return obj[e];

  const normalizedKey = e.replaceAll(" ", "");

  return obj[normalizedKey] || e;
};
