import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { twMerge } from "tailwind-merge";
import type { MenuItem } from "../components/organisms/sidebar";
import { iranyekanX, iranyekanXFaNum } from "../fonts";
import "./globals.css";
import MainLayout from "../components/templates/layout/mainLayout";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const menuItems: MenuItem[] = [
    {
      title: "داشبورد",
      icon: "Dashboard",
      href: "/",
    },

    {
      title: "مدیریت کاربران",
      icon: "User",
      href: "/users",
    },

    {
      title: "مدیریت نقش‌ها",
      icon: "Users",
      href: "/roles",
    },

    {
      title: "مدیریت سفارشات",
      icon: "Headphone",
      children: [
        { title: "لیست سفارشات", href: "/orders" },
        { title: "سفارشات تکمیل‌شده (0)", href: "/orders/completed" },
        { title: "در حال بررسی (0)", href: "/orders/under-review" },
        { title: "نیاز به اطلاعات (0)", href: "/orders/get-info" },
        { title: "برچسب‌ها", href: "/orders/labels" },
      ],
    },

    {
      title: "مدیریت نظرات",
      icon: "Messages",
      children: [
        { title: "نظرات بلاگ", href: "/comments/blogs" },
        { title: "نظرات محصولات", href: "/comments/product" },
      ],
    },

    {
      title: "مدیریت محتوا",
      icon: "Blog",
      children: [
        { title: "بلاگ‌ها", href: "/posts/blogs" },
        { title: "اخبار", href: "/posts/news" },
        { title: "تگ‌ها", href: "/posts/tags" },
        { title: "دسته‌بندی‌ها", href: "/posts/categories" },
        { title: "سوالات متداول", href: "/posts/faq" },
        { title: "درباره ما", href: "/posts/about-us" },
      ],
    },

    {
      title: "مدیریت محصولات",
      icon: "WidgetAdd",
      children: [
        { title: "لیست محصولات", href: "/products" },
        { title: "دسته‌بندی محصولات", href: "/products/categories" },
        { title: "محصولات پیشنهادی", href: "/products/suggested" },
        { title: "لیست تخفیف‌ها", href: "/products/discounts" },
        { title: "هشدارها", href: "/products/alerts" },
      ],
    },

    {
      title: "مدیریت اپل آیدی",
      icon: "Apple",
      children: [
        { title: "لیست اپل آیدی", href: "/apple-ids" },
        { title: "دسته‌بندی کشورها", href: "/apple-ids/categories" },
        { title: "افزودن اپل آیدی", href: "/apple-ids/add" },
        { title: "لاگ‌ها", href: "/apple-ids/logs" },
        { title: "سوالات امنیتی", href: "/apple-ids/questions" },
      ],
    },

    {
      title: "مدیریت مالی",
      icon: "WidgetAdd",
      children: [
        { title: "پکیج‌های پیشنهادی", href: "/financial/suggested-packages" },
        { title: "مدیریت کیف پول کاربران", href: "/financial/wallets" },
        { title: "مدیریت تراکنش‌ها", href: "/financial/transactions" },
        { title: "مدیریت فروش", href: "/financial/sale" },
      ],
    },

    {
      title: "تماس با ما",
      icon: "Phone",
      href: "/tickets",
    },

    {
      title: "مدیریت سایت",
      icon: "Permission",
      children: [
        { title: "لیست فرم‌ها", href: "/management/forms" },
        { title: "ایجاد فرم جدید", href: "/management/forms/create/structure" },
        { title: "لاگ‌های ادمین", href: "/management/admins" },
        { title: "گزارشات زمانی", href: "/management/timing/dashboard" },
      ],
    },

    {
      title: "تنظیمات سایت",
      icon: "Setting",
      href: "/settings",
    },
  ];

  return (
    <html lang="fa">
      <body
        className={twMerge(
          iranyekanX.variable,
          iranyekanXFaNum.variable,
          "font-IRANYekan-x"
        )}
      >
        <MainLayout loading={false} locale="fa" role={{is_client:false}} menuItems={menuItems}>
        {children}
        </MainLayout>
      </body>
    </html>
  );
}
