import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { twMerge } from "tailwind-merge";
import { iranyekanX, iranyekanXFaNum } from "../fonts";
import "./globals.css";
import MainLayout from "../components/templates/layout/mainLayout";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa">
      <body
        className={twMerge(
          iranyekanX.variable,
          iranyekanXFaNum.variable,
          "font-IRANYekan-x"
        )}
      >
        <MainLayout loading={false} locale="fa" role={{is_client:false}}>
        {children}
        </MainLayout>
      </body>
    </html>
  );
}
