import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { twMerge } from "tailwind-merge";
import { iranyekanX, iranyekanXFaNum } from "../fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          iranyekanX.variable,
          iranyekanXFaNum.variable,
          "font-IRANYekan-x"
        )}
      >
        {children}
      </body>
    </html>
  );
}
